import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@components/Nav";
import { NextAuthProvider } from "@components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='main'></div>
        <main className='app'>
          <NextAuthProvider>
            <Nav />
            {children}
          </NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
